version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ek-cicd/
hooks:
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
