version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-deployment-staging-area
permissions:
  - object: /tmp/codedeploy-deployment-staging-area
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
