version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-deployment-staging-area
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
